[2025-07-04T15:26:58.764+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T09:56:51.115733+00:00 [queued]>
[2025-07-04T15:26:58.772+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T09:56:51.115733+00:00 [queued]>
[2025-07-04T15:26:58.773+0530] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-04T15:26:58.790+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): check_raw_file> on 2025-07-04 09:56:51.115733+00:00
[2025-07-04T15:26:58.793+0530] {standard_task_runner.py:57} INFO - Started process 22010 to run task
[2025-07-04T15:26:58.802+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'check_raw_file', 'manual__2025-07-04T09:56:51.115733+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmpe8v7cc7w']
[2025-07-04T15:26:58.806+0530] {standard_task_runner.py:85} INFO - Job 13: Subtask check_raw_file
[2025-07-04T15:26:58.862+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T09:56:51.115733+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T15:26:58.927+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='check_raw_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T09:56:51.115733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T09:56:51.115733+00:00'
[2025-07-04T15:26:58.931+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T15:26:58.932+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'test -f data/raw/OnlineRetail.csv || (echo "Missing data/raw/OnlineRetail.csv. Please download and place it in data/raw/" && exit 1)']
[2025-07-04T15:26:58.940+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T15:26:58.946+0530] {subprocess.py:93} INFO - Missing data/raw/OnlineRetail.csv. Please download and place it in data/raw/
[2025-07-04T15:26:58.947+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-04T15:26:58.957+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-04T15:26:58.966+0530] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=retail_etl_dag, task_id=check_raw_file, execution_date=20250704T095651, start_date=20250704T095658, end_date=20250704T095658
[2025-07-04T15:26:58.981+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task check_raw_file (Bash command failed. The command returned a non-zero exit code 1.; 22010)
[2025-07-04T15:26:59.012+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T15:26:59.039+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
