[2025-07-04T15:44:37.262+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T10:09:25.863525+00:00 [queued]>
[2025-07-04T15:44:37.271+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T10:09:25.863525+00:00 [queued]>
[2025-07-04T15:44:37.272+0530] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-07-04T15:44:37.289+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): check_raw_file> on 2025-07-04 10:09:25.863525+00:00
[2025-07-04T15:44:37.292+0530] {standard_task_runner.py:57} INFO - Started process 24455 to run task
[2025-07-04T15:44:37.300+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'check_raw_file', 'manual__2025-07-04T10:09:25.863525+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmp0_mzetva']
[2025-07-04T15:44:37.305+0530] {standard_task_runner.py:85} INFO - Job 22: Subtask check_raw_file
[2025-07-04T15:44:37.360+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.check_raw_file manual__2025-07-04T10:09:25.863525+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T15:44:37.420+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='check_raw_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T10:09:25.863525+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T10:09:25.863525+00:00'
[2025-07-04T15:44:37.423+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T15:44:37.424+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'test -f "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/airflow_home/data/raw/OnlineRetail.csv" || (echo "Missing /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/airflow_home/data/raw/OnlineRetail.csv. Please download and place it." && exit 1)']
[2025-07-04T15:44:37.432+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T15:44:37.438+0530] {subprocess.py:93} INFO - Missing /Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/airflow_home/data/raw/OnlineRetail.csv. Please download and place it.
[2025-07-04T15:44:37.439+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-04T15:44:37.448+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-04T15:44:37.453+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=retail_etl_dag, task_id=check_raw_file, execution_date=20250704T100925, start_date=20250704T101437, end_date=20250704T101437
[2025-07-04T15:44:37.466+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 22 for task check_raw_file (Bash command failed. The command returned a non-zero exit code 1.; 24455)
[2025-07-04T15:44:37.513+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T15:44:37.546+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
