[2025-07-04T15:31:57.768+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T15:31:57.775+0530] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: retail_etl_dag.check_raw_file scheduled__2025-07-03T00:00:00+00:00 [queued]>
[2025-07-04T15:31:57.775+0530] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-07-04T15:31:57.792+0530] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): check_raw_file> on 2025-07-03 00:00:00+00:00
[2025-07-04T15:31:57.797+0530] {standard_task_runner.py:57} INFO - Started process 22650 to run task
[2025-07-04T15:31:57.807+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'retail_etl_dag', 'check_raw_file', 'scheduled__2025-07-03T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/retail_etl_dag.py', '--cfg-path', '/var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T/tmp4_1d6fr2']
[2025-07-04T15:31:57.811+0530] {standard_task_runner.py:85} INFO - Job 14: Subtask check_raw_file
[2025-07-04T15:31:57.878+0530] {task_command.py:416} INFO - Running <TaskInstance: retail_etl_dag.check_raw_file scheduled__2025-07-03T00:00:00+00:00 [running]> on host v-macbook-pro.local
[2025-07-04T15:31:57.953+0530] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='retail_etl_dag' AIRFLOW_CTX_TASK_ID='check_raw_file' AIRFLOW_CTX_EXECUTION_DATE='2025-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-03T00:00:00+00:00'
[2025-07-04T15:31:57.957+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/53/tbd296vx2878lwlskxvm_8h80000gp/T
[2025-07-04T15:31:57.959+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'test -f data/raw/OnlineRetail.csv || (echo "Missing data/raw/OnlineRetail.csv. Please download and place it in data/raw/" && exit 1)']
[2025-07-04T15:31:57.968+0530] {subprocess.py:86} INFO - Output:
[2025-07-04T15:31:57.978+0530] {subprocess.py:93} INFO - Missing data/raw/OnlineRetail.csv. Please download and place it in data/raw/
[2025-07-04T15:31:57.979+0530] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-04T15:31:57.991+0530] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/vaish/databorn_etl_project/retail_etl/etl_pipeline_project/venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-04T15:31:57.998+0530] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=retail_etl_dag, task_id=check_raw_file, execution_date=20250703T000000, start_date=20250704T100157, end_date=20250704T100157
[2025-07-04T15:31:58.013+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task check_raw_file (Bash command failed. The command returned a non-zero exit code 1.; 22650)
[2025-07-04T15:31:58.061+0530] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-04T15:31:58.088+0530] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
